---
plugin: aws_ec2
boto_profile: baxter
regions:
  - us-west-2
filters:
  instance-state-name: running
  tag:Department: Development
  tag:Name: 
    - dev-stepandb
hostnames:
  - private-ip-address
  - tag:Name
keyed_groups:
  - prefix: tag
    key: tags
