---
- name: Installing CW awslogs agent for Prophet-web logs
  hosts: tag_Name_dev_stepan, tag_Name_ia_beckman, tag_Name_oberon
  serial: 1
  any_errors_fatal: true
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
    - include_role:
        name: awslogs-agent-web
